[package]
name = "trs"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.13"
reqwest = { version = "0.12.20", features = ["blocking"] }
rusqlite = { version = "0.36.0", features = ["bundled"] }
xml-rs = "0.8.26"
